version: '3.5'

services: 
  mysql_server: 
    image: mysql:8
    command: mysqld --bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=CatQuizlet
      