import type { Metadata } from "next";
import { Autour_One } from "next/font/google";
import "./globals.css";

const autourOne = Autour_One({
  variable: "--font-autour-one",
  subsets: ["latin"],
  weight: "400", // Adjust if the font supports multiple weights
});

export const metadata: Metadata = {
  title: "Cat Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={autourOne.className}>
        {children}
      </body>
    </html>
  );
}
